apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: hello-trigger-binding
spec:
  params:
    - name: repository
      value: "https://github.com/danielbu-ibm/Tekton-Tutorial"
    - name: branch
      value: "master"
#    - name: repository
#      value: $(event.repository.html_url)
#    - name: branch
#      value: $(event.pull_request.head.ref)